### ISSUE TITLE
Hey I think you made a typo on the docs

### ISSUE THREAD

**Issue by mas6y6** [antonvh/UartRemote#10]
Hey I think you made a typo on the docs that installs spike
on the line that says

"""
To use the library include the following line in your python code:

```
from project.uartremote import *
```
"""

its supposed to be

"""
To use the library include the following line in your python code:

```
from projects.uartremote import *
```
"""

On https://uartremote.readthedocs.io/

**Comment by antonvh** [comment]
I fixed it. Most of the docs are here, these days: https://docs.antonsmindstorms.com/en/latest/
