### ISSUE TITLE
Discussion group

### ISSUE THREAD

**Issue by SpudGunMan** [antonvh/UartRemote#5]
Do you have a existing discussion group/chat/discord location for your projects?

**Comment by antonvh** [comment]
No. I figured github issues would be good enough. What are you missing and what would you suggest?

**Comment by antonvh** [comment]
Actually, we have a trello and a signal group. Let me think about a scalable solution.

**Comment by NafetsReruam** [comment]
Is it possible to use the library on an Arduino Uno?
I get compiler errors regarding these includes:
#include <cstdio>
#include <iostream>
#include <unordered_map>

**Comment by NafetsReruam** [comment]
OK. Including cstdio, iostream and unordered_map is apparently unnecessary as these libraries are not used at all. I just removed the includes, was able to compile it and it ultimately worked with the Arduino Uno.
Thanks for your work

**Comment by cent0** [comment]
Nice to meet
Not understand but this module code
Have this function?
(Mcu uart)TX RX pin < - > ESP <-> ESP<->(Mcu uart)TX RX pin

THANKS

**Comment by antonvh** [comment]
I'm sorry, can you elaborate? What are you trying to achieve?

**Comment by cent0** [comment]
I need estend 4wire one lcd module to nowire system. on board have stm mcu. Connected to 4 wire to other mcu.Dspic33.
I have check the voltage line data is 3.3v have 2 wire TX and rx. Master and slave?

Hey sir we have test with multimeter with new battery the voltage is 3.2V peak..
This is two line 3V TX and RX

**Comment by antonvh** [comment]
You could make a passthrough:

https://docs.micropython.org/en/latest/pyboard/tutorial/pass_through.html

But of course from wifi or bt instead of USB. So you need some connection logic code.

**Comment by cent0** [comment]
@antonvh we have found this
https://github.com/rkubera/ESP8266-RC-Transmitter-Receiver
🤔🤔
This work for my project🤔but only two pin connected to hardware uart

**Comment by antonvh** [comment]
Great! Community and discussion are now here:
https://mm.antonsmindstorms.com/login

Send me a message or email if you want to join!

**Comment by cent0** [comment]
Hello antonvh not have telegram group?
I not have account for this

Thank s

**Comment by antonvh** [comment]
No. Only mattermost. Send me an email and I wil add you.

**Comment by cent0** [comment]
Hello sir this need business email. No work with Gmail or hotmail

**Comment by cent0** [comment]
I have send email to you  i wait reply

**Comment by antonvh** [comment]
You should have an invite by now?

**Comment by cent0** [comment]
Opss email have chat live with Github 😀
I have make a little video published to YouTube for capturing data uart.

https://youtu.be/OS6ndO4Ey-Q

In this video show captured data speed is OK.
In The recevied data is visible ID device is printed in the data hex table.
The display have one time chip 8pin. And this display need send date to internal machine for working fine. 
The captured data bits in the table hex have the year Mont and day!  Pretty
Other data is W instant power, power on demand, voltage dc, and voltage ac. But have scale bit 0 255  and the display measure 0w to 1998 max. I need more test for find the correct payload, thank you for support if have news tell me for finish the project.
Thank you

**Comment by cent0** [comment]
![Videoframe_20221024_213645_com huawei himovie overseas](https://user-images.githubusercontent.com/39629876/197610904-af11a4b4-b919-4b89-92f6-66e9c4081dba.jpg)

In the picute size for packet transmitted 50 and 350

**Comment by cent0** [comment]
Have any help dor decondig this? I Hare registered to mattermost anton
